import type { Exporter } from './types'
import { buildExportDocument, deriveExportFilename, escapeXml } from './utils'

const CELL_SIZE = 18
const FONT_FAMILY = "'Fira Code', 'IBM Plex Mono', 'DM Mono', monospace"

export const svgExporter: Exporter = {
  id: 'svg',
  label: 'SVG',
  description: 'Vector export with layer-ordered glyphs and palette-aware colors.',
  extension: 'svg',
  run: ({ document, selection, scope, padding, filename }) => {
    const exportDocument = buildExportDocument({ document, selection, scope, padding })
    const width = exportDocument.width * CELL_SIZE
    const height = exportDocument.height * CELL_SIZE

    const layerOrder = [...exportDocument.layers].sort((a, b) => a.zIndex - b.zIndex)
    const glyphElements: string[] = []

    layerOrder.forEach((layer) => {
      layer.glyphs.forEach((glyph) => {
        const baseX = glyph.position.x * CELL_SIZE
        const baseY = glyph.position.y * CELL_SIZE

        const textX = baseX + CELL_SIZE / 2
        const textY = baseY + CELL_SIZE / 2 + 0.5
        const glyphGroups = glyph.groupIds.length ? ` data-groups="${escapeXml(glyph.groupIds.join(','))}"` : ''
        const textFill = glyph.foreground ?? '#FFFFFF'

        const text = `<text x="${textX.toFixed(2)}" y="${textY.toFixed(2)}" fill="${textFill}" font-size="${CELL_SIZE * 0.74}" font-family="${FONT_FAMILY}" text-anchor="middle" dominant-baseline="middle">${escapeXml(glyph.char)}</text>`

        glyphElements.push(`<g data-layer="${escapeXml(layer.id)}"${glyphGroups}>${text}</g>`)
      })
    })

    const content = [
      '<?xml version="1.0" encoding="UTF-8"?>',
      '<!-- Generated by ASCII Asset Studio -->',
      `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" shape-rendering="crispEdges">`,
      '  <rect width="100%" height="100%" fill="transparent" />',
      glyphElements.map((element) => `  ${element}`).join('\n'),
      '</svg>',
    ].join('\n')

    return {
      filename:
        filename ??
        deriveExportFilename(
          document,
          scope,
          'svg',
          document.name ?? 'asset',
        ),
      mimeType: 'image/svg+xml',
      content,
    }
  },
}
